version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "127.0.0.1:8080:8080"  # WebSocket port
      - "8081:8081"            # TCP port
    environment:
      - NODE_ENV=production
      - TZ=UTC
    restart: unless-stopped
    networks:
      app-network:
        aliases:
          - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16 