version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - NODE_ENV=production 